#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
Usage: scripts/upgrade-ai-os.sh --target TARGET_DIR [--force]
USAGE
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

target=""
force=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      target="${2:-}"
      shift 2
      ;;
    --force)
      force=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 2
      ;;
  esac
done

if [[ -z "$target" ]]; then
  echo "Missing required option: --target" >&2
  usage
  exit 2
fi

mkdir -p "$target"
target="$(cd "$target" && pwd)"

copy_file() {
  local src="$1"
  local dest="$2"

  # Version metadata should always reflect the installed template version.
  if [[ "$(basename "$dest")" != "AI_OS_VERSION" && -e "$dest" && "$force" != true ]]; then
    echo "Preserving existing file: $dest"
    return 0
  fi

  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
}

copy_tree() {
  local rel="$1"
  local src_root="$repo_root/$rel"

  [[ -d "$src_root" ]] || return 0

  while IFS= read -r src; do
    local relative="${src#"$repo_root/"}"

    # Project-specific rules are generated by init-ai-os, not upgraded blindly.
    if [[ "$relative" == "harness/ai-rules.md" ]]; then
      continue
    fi

    # Internal planning docs are not part of installed project runtime.
    if [[ "$relative" == docs/superpowers/* ]]; then
      continue
    fi

    copy_file "$src" "$target/$relative"
  done < <(find "$src_root" -type f | sort)
}

copy_tree ".github"
copy_tree "harness"
copy_tree "memory"
copy_tree "scripts"
copy_tree "skills"
copy_tree "templates"
copy_tree "docs"
copy_file "$repo_root/ai-os.project.example.yml" "$target/ai-os.project.example.yml"
copy_file "$repo_root/AI_OS_VERSION" "$target/AI_OS_VERSION"
copy_file "$repo_root/install.sh" "$target/install.sh"

echo "Upgraded AI OS in $target"
